name: autotrie
description: A auto-completion engine for Dart/Flutter, based around an optimized Trie implementation.
version: 1.0.0+2
homepage: https://github.com/AKushWarrior/autotrie
repository: https://github.com/AKushWarrior/autotrie
issue_tracker: https://github.com/AKushWarrior/autotrie/issues

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  hive: ^3.0.0-dev
  meta: ^1.9.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
